version: '3.8'

services:
  # ==========================================
  # CAPA DE DATOS (Se levanta manualmente en ec2_datos)
  # ==========================================
  database:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: adminpassword123
      MYSQL_DATABASE: proyecto_db
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  # ==========================================
  # CAPA DE APLICACIÓN (Se levanta vía GitHub Actions)
  # ==========================================
  ventas-backend:
    image: omarffduoc/ventas-backend:latest
    container_name: ventas-app
    ports:
      - "0.0.0.0:8080:8080" # <--- Exponer a todas las interfaces
    environment:
      - DB_ENDPOINT=${DB_IP_DATOS}
      - DB_PORT=3306
      - DB_NAME=proyecto_db
      - DB_USERNAME=root
      - DB_PASSWORD=adminpassword123
    restart: always

  despachos-backend:
    image: omarffduoc/despachos-backend:latest
    container_name: despachos-app
    ports:
      - "0.0.0.0:8081:8081" # <--- Exponer a todas las interfaces
    environment:
      - DB_ENDPOINT=${DB_IP_DATOS}
      - DB_PORT=3306
      - DB_NAME=proyecto_db
      - DB_USERNAME=root
      - DB_PASSWORD=adminpassword123
    restart: always

  # ==========================================
  # CAPA WEB / FRONTEND (Se levanta vía GitHub Actions)
  # ==========================================
  frontend:
    image: omarffduoc/frontend:latest
    container_name: frontend-app
    ports:
      - "0.0.0.0:80:80" # <--- Asegurarnos de que el frontend también esté expuesto
    restart: always

volumes:
  mysql_data: