version: '3.8'

services:
  # ==========================================
  # 1. EL PORTERO (NGINX) - El único expuesto
  # ==========================================
  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    ports:
      - "0.0.0.0:80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always

  # ==========================================
  # 2. CAPA WEB / FRONTEND (Oculto)
  # ==========================================
  frontend:
    image: omarffduoc/frontend:latest
    container_name: frontend-app
    restart: always

  # ==========================================
  # 3. CAPA DE APLICACIÓN (Ocultos)
  # ==========================================
  ventas-backend:
    image: omarffduoc/ventas-backend:latest
    container_name: ventas-app
    environment:
      - DB_ENDPOINT=${DB_IP_DATOS}
      - DB_PORT=3306
      - DB_NAME=proyecto_db
      - DB_USERNAME=root
      - DB_PASSWORD=adminpassword123
    restart: always

  despachos-backend:
    image: omarffduoc/despachos-backend:latest
    container_name: despachos-app
    environment:
      - DB_ENDPOINT=${DB_IP_DATOS}
      - DB_PORT=3306
      - DB_NAME=proyecto_db
      - DB_USERNAME=root
      - DB_PASSWORD=adminpassword123
    restart: always

  # ==========================================
  # CAPA DE DATOS (Se levanta manualmente en ec2-datos)
  # ==========================================
  database:
    image: mysql:8.0
    container_name: mysql-db
    command: --bind-address=0.0.0.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: adminpassword123
      MYSQL_DATABASE: proyecto_db
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data: