events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        # 1. Todo lo que vaya a la raíz (/) se va al Frontend
        location / {
            proxy_pass http://frontend:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 2. Todo lo que empiece con /api/v1/ventas se va al backend de ventas
        location /api/v1/ventas {
            proxy_pass http://ventas-backend:8080/api/v1/ventas;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 3. Todo lo que empiece con /api/v1/despachos se va al backend de despachos
        location /api/v1/despachos {
            proxy_pass http://despachos-backend:8081/api/v1/despachos;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}