apiVersion: apps/v1
kind: Deployment
metadata:
  name: ventas-app
  namespace: tienda
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ventas-app
  template:
    metadata:
      labels:
        app: ventas-app
    spec:
      containers:
        - name: ventas
          image: 417651015767.dkr.ecr.us-east-1.amazonaws.com/proyecto-ventas:eks-v1
          imagePullPolicy: Always
          env:
            - name: DB_ENDPOINT
              value: "db-service"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "proyecto_db"
            - name: DB_USERNAME
              value: "root"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: despachos-app
  namespace: tienda
spec:
  replicas: 2
  selector:
    matchLabels:
      app: despachos-app
  template:
    metadata:
      labels:
        app: despachos-app
    spec:
      containers:
        - name: despachos
          image: 417651015767.dkr.ecr.us-east-1.amazonaws.com/proyecto-despachos:eks-v1
          imagePullPolicy: Always
          env:
            - name: DB_ENDPOINT
              value: "db-service"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "proyecto_db"
            - name: DB_USERNAME
              value: "root"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
          ports:
            - containerPort: 8081