name: CI/CD Pipeline

on:
  push:
    branches: [ deploy ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Backends/Frontend
        run: |
          docker build -t omarffduoc/ventas-backend:latest ./back-Ventas_SpringBoot/Springboot-API-REST
          docker push omarffduoc/ventas-backend:latest
          docker build -t omarffduoc/despachos-backend:latest ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
          docker push omarffduoc/despachos-backend:latest
          docker build -t omarffduoc/frontend:latest ./front_despacho
          docker push omarffduoc/frontend:latest

  deploy-to-ec2:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/Devops
            sudo chown -R ec2-user:ec2-user .
            git fetch --all
            git reset --hard origin/deploy
            sudo docker-compose pull
            sudo docker-compose up -d --remove-orphans