name: CI/CD Pipeline - Despachos

on:
  push:
    branches: [ deploy ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Ventas
        uses: docker/build-push-action@v5
        with:
          context: ./back-Ventas_SpringBoot/Springboot-API-REST
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ventas-backend:latest

      - name: Build and Push Despachos
        uses: docker/build-push-action@v5
        with:
          context: ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/despachos-backend:latest

      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./front_despacho
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest

  deploy-to-ec2:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 1. Corregir permisos de propiedad de la carpeta para ec2-user
            sudo chown -R ec2-user:ec2-user /home/ec2-user/Devops
            
            # 2. Configurar Git como seguro
            git config --global --add safe.directory /home/ec2-user/Devops
            
            # 3. Navegar y limpiar posibles bloqueos de Git
            cd /home/ec2-user/Devops
            rm -f .git/index.lock
            
            # 4. Pull forzado para ignorar discrepancias locales
            git fetch --all
            git reset --hard origin/deploy
            
            # 5. Despliegue con Docker Compose
            docker-compose pull
            docker-compose up -d --remove-orphans