name: Deploy Frontend to EKS

on:
  push:
    branches:
      - deploy
    paths:
      - 'front_despacho/**'
      - 'k8s/frontend-deployment.yaml'
      - 'k8s/frontend-service.yaml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Frontend Image to ECR
        run: |
          docker build -t 417651015767.dkr.ecr.us-east-1.amazonaws.com/proyecto-frontend:eks-v1 ./front_despacho
          docker push 417651015767.dkr.ecr.us-east-1.amazonaws.com/proyecto-frontend:eks-v1

      - name: Update Kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --name eva3-eks --region us-east-1

      - name: Deploy and Restart Pods on EKS
        run: |
          kubectl apply -f k8s/namespace.yaml
          kubectl apply -f k8s/frontend-deployment.yaml
          kubectl apply -f k8s/frontend-service.yaml
          kubectl rollout restart deployment/frontend-app -n tienda
          kubectl rollout restart deployment/reverse-proxy -n tienda